# Generated by Django 4.0.4 on 2022-05-10 19:17

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=191)),
                ('name', models.CharField(max_length=191)),
                ('image', models.ImageField(upload_to=app.models.get_file_path)),
                ('desc', models.TextField(max_length=500)),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=trending')),
                ('meta_title', models.CharField(max_length=191)),
                ('meta_keywords', models.CharField(max_length=191)),
                ('meta_desc', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=191)),
                ('product_name', models.CharField(max_length=191)),
                ('product_image', models.ImageField(upload_to=app.models.get_file_path)),
                ('quantity', models.IntegerField()),
                ('product_desc', models.TextField(max_length=500)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=trending')),
                ('meta_title', models.CharField(max_length=191)),
                ('meta_keywords', models.CharField(max_length=191)),
                ('meta_desc', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
