# Generated by Django 4.0.4 on 2022-05-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_product_name_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_desc',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
