# Generated by Django 4.0.4 on 2022-05-18 12:53

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_small_desc_product_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='sliderimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=191)),
                ('name', models.CharField(max_length=191)),
                ('image', models.ImageField(upload_to=app.models.get_file_path)),
                ('desc', models.TextField(max_length=500)),
                ('small_desc', models.TextField(max_length=250, null=True)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
