# Generated by Django 4.0.4 on 2022-05-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_konkan_alter_order_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='konkan',
        ),
    ]
