# Generated by Django 4.0.4 on 2022-05-28 14:01

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_product_konkan'),
    ]

    operations = [
        migrations.CreateModel(
            name='konkan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=191)),
                ('name', models.CharField(max_length=191)),
                ('product_image', models.ImageField(upload_to=app.models.get_file_path)),
                ('small_desc', models.TextField(max_length=250, null=True)),
                ('quantity', models.IntegerField()),
                ('product_desc', models.TextField(max_length=500)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('konkan_trending', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('tag', models.CharField(max_length=150, null=True)),
                ('meta_title', models.CharField(max_length=191)),
                ('meta_keywords', models.CharField(max_length=191)),
                ('meta_desc', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
