# Generated by Django 4.0.4 on 2022-05-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_konkan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='konkan',
        ),
    ]
