# Generated by Django 4.0.4 on 2022-05-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_konkan'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_prod',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
