# Generated by Django 4.0.4 on 2022-05-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_product_qty_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='best_deal',
            field=models.BooleanField(default=False, help_text='0=default, 1=best_deal'),
        ),
    ]
