# Generated by Django 4.0.4 on 2022-05-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_product_vegitables'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dal',
            field=models.BooleanField(default=False, help_text='0=default, 1=Dal'),
        ),
        migrations.AddField(
            model_name='product',
            name='dry_fruits',
            field=models.BooleanField(default=False, help_text='0=default, 1=Dry_fruits'),
        ),
        migrations.AddField(
            model_name='product',
            name='fruits',
            field=models.BooleanField(default=False, help_text='0=default, 1=Fruits'),
        ),
        migrations.AddField(
            model_name='product',
            name='harbs',
            field=models.BooleanField(default=False, help_text='0=default, 1=Harbs'),
        ),
        migrations.AddField(
            model_name='product',
            name='masale',
            field=models.BooleanField(default=False, help_text='0=default, 1=Masale'),
        ),
    ]
