# Generated by Django 4.0.4 on 2022-06-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_product_dal_product_dry_fruits_product_fruits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='farming_product',
            field=models.BooleanField(default=False, help_text='0=default, 1=Farming_product'),
        ),
    ]
