# Generated by Django 4.0.4 on 2022-06-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_product_farming_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fertilizer',
            field=models.BooleanField(default=False, help_text='0=default, 1=Fertilizer'),
        ),
    ]
