# Generated by Django 4.0.4 on 2022-06-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_product_farming_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_qty',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
